export const ADD_NEW_NICKNAME_SUCCESS = 'ADD_NEW_NICKNAME_SUCCESS';

export const GET_ALL_MESSAGES_SUCCESS = 'GET_ALL_MESSAGES_SUCCESS';
export const GET_LATEST_MESSAGES_SUCCESS = 'GET_LATEST_MESSAGES_SUCCESS';